git-integration-for-jira-cloud/azure-devops-server-lifecycle-policies-gij-cloud.md
git-integration-for-jira-cloud/basic-commands-gij-cloud.md
git-integration-for-jira-cloud/code-syntax-highlighter-gij-cloud.md
git-integration-for-jira-cloud/connecting-ssh-git-repositories-to-jira-cloud-gij-cloud.md

GIJ cloud articles modified 2022-06-14

---

git-integration-for-jira-cloud/why-dont-i-see-commits-git-integration-for-cloud-gij-cloud.md
git-integration-for-jira-cloud/why-dont-i-see-the-create-branch-or-pull-request-features-gij-cloud.md
git-integration-for-jira-cloud/workflow-transitions-gij-cloud.md
git-integration-for-jira-cloud/working-with-custom-api-path-gij-cloud.md
git-integration-for-jira-cloud/working-with-ssh-keys-gij-cloud.md

why-dont-i-see-commits-git-integration-for-cloud-gij-cloud.md
why-dont-i-see-the-create-branch-or-pull-request-features-gij-cloud.md
workflow-transitions-gij-cloud.md
working-with-custom-api-path-gij-cloud.md
working-with-ssh-keys-gij-cloud.md

Checked files, made some corrections

---

git-integration-for-jira-cloud/aws-codecommit-webhook-events-gij-cloud.md
git-integration-for-jira-cloud/bitbucket-webhook-events-gij-cloud.md
git-integration-for-jira-cloud/github-webhook-events-gij-cloud.md
git-integration-for-jira-cloud/gitlab-webhook-events-gij-cloud.md
git-integration-for-jira-cloud/indexing-triggers-gij-cloud.md
git-integration-for-jira-cloud/microsoft-webhook-events-gij-cloud.md
git-integration-for-jira-cloud/using-the-git-service-integration-wizard-gij-cloud.md
git-integration-for-jira-cloud/using-the-repository-browser-gij-cloud.md
git-integration-for-jira-cloud/using-the-single-git-integration-wizard-gij-cloud.md
git-integration-for-jira-cloud/webhook-indexing-explainer-gij-cloud.md
git-integration-for-jira-cloud/webhook-indexing-integration-gij-cloud.md

Mk 300 update git cloud docs main

---

git-integration-for-jira-cloud/allow-list-whitelist-bigbrassband-cloud-gij-cloud.md

New updated whitelist IP addresses were applied to the whiltelist doc.

INF-1406 Add/update proxy IP addresses for whitelisting

---

git-integration-for-jira-cloud/git-integration-for-jira-home-gij-cloud.md

Updating link to new support form

---

git-integration-for-jira-cloud/git-integration-server-data-center-vs-jira-cloud-feature-comparison-gij-cloud.md

This took me longer.... trial and error on which layout would be best and had to resort to HTML table to contain tricky parts.

MK-300 / GITCL-3059 Fix table format links, layout and fix missing images

---

git-integration-for-jira-cloud/github-com-gij-cloud.md
git-integration-for-jira-cloud/github-enterprise-server-gij-cloud.md
git-integration-for-jira-cloud/gitlab-ce-ee-gij-cloud.md

Fix containers, links, formatting etc

MK-300 / GITCL-3059 Update formats

---

git-integration-for-jira-cloud/allow-list-whitelist-bigbrassband-cloud-gij-cloud.md

Updating whitelist IP Address to reflect new EU-West region IP address

EU Region IP address update

---

git-integration-for-jira-cloud/creating-personal-access-tokens-gij-cloud.md

GIT-5152 Remove old info

---

git-integration-for-jira-cloud/connection-error-for-self-hosted-git-servers-gij-cloud.md
git-integration-for-jira-cloud/empty-list-of-repositories-after-integration-of-azure-repos-gij-cloud.md
git-integration-for-jira-cloud/error-while-reindexing-java-heap-space-object-too-large-rejecting-the-pack-gij-cloud.md
git-integration-for-jira-cloud/licensing-error-installcheck-failed-gij-cloud.md
git-integration-for-jira-cloud/oauth-connection-error-or-error-401-page-with-azure-devops-integration-gij-cloud.md
git-integration-for-jira-cloud/oauth-connection-error-or-error-401-page-with-azure-devops-with-active-directory-integration-gij-cloud.md
git-integration-for-jira-cloud/reconnecting-azure-devops-and-vsts-oauth-integrations-gij-cloud.md
git-integration-for-jira-cloud/repositories-missing-from-azure-devops-or-vsts-integration-gij-cloud.md
git-integration-for-jira-cloud/ssh-key-file-format-is-invalid-gij-cloud.md
git-integration-for-jira-cloud/why-dont-i-see-commits-git-integration-for-cloud-gij-cloud.md
git-integration-for-jira-cloud/why-dont-i-see-the-create-branch-or-pull-request-features-gij-cloud.md

Change all BBB refs to GK and fix support links
Fix code blocks

GITCL-3418 Update formats, old imgs, steps etc.

---

git-integration-for-jira-cloud/app-support-gij-cloud.md
git-integration-for-jira-cloud/general-settings-for-administrators-gij-cloud.md
git-integration-for-jira-cloud/general-settings-gij-cloud.md

Fix imgs not displaying
Replace old imgs
---
Add new version support info
Add new EOL support dates

GITCL-3418 Update/fix old imgs, steps etc.

---

git-integration-for-jira-cloud/adding-webhooks-for-gitlab-repository-gij-cloud.md
git-integration-for-jira-cloud/advanced-clear-development-information-setting-gij-cloud.md
git-integration-for-jira-cloud/associating-git-commits-manually-to-jira-issues-gij-cloud.md
git-integration-for-jira-cloud/aws-codecommit-gij-cloud.md
git-integration-for-jira-cloud/development-information-views-gij-cloud.md
git-integration-for-jira-cloud/faq-administration-gij-cloud.md
git-integration-for-jira-cloud/faq-developer-gij-cloud.md
git-integration-for-jira-cloud/faq-general-gij-cloud.md
git-integration-for-jira-cloud/faq-installation-and-setup-gij-cloud.md
git-integration-for-jira-cloud/faq-purchase-and-pricing-gij-cloud.md
git-integration-for-jira-cloud/faq-reindex-gij-cloud.md
git-integration-for-jira-cloud/faq-repositories-gij-cloud.md
git-integration-for-jira-cloud/faq-ssh-gij-cloud.md
git-integration-for-jira-cloud/git-commits-issue-tab-and-project-page-gij-cloud.md
git-integration-for-jira-cloud/git-integration-options-gij-cloud.md
git-integration-for-jira-cloud/gitkraken-integration-settings-gij-cloud.md
git-integration-for-jira-cloud/gitlens-integration-settings-gij-cloud.md
git-integration-for-jira-cloud/jira-development-information-gij-cloud.md
git-integration-for-jira-cloud/jira-development-information-settings-features-gij-cloud.md
git-integration-for-jira-cloud/jira-development-information-settings-gij-cloud.md
git-integration-for-jira-cloud/jql-searching-for-commits-and-pull-requests-gij-cloud.md
git-integration-for-jira-cloud/repository-browser-settings-gij-cloud.md

GIT-5270 / GITCL-3418 Update formatting, old imgs, steps, etc.

---

git-integration-for-jira-cloud/enable-git-integration-app-smart-commits-setting-gij-cloud.md
git-integration-for-jira-cloud/enable-jira-cloud-smart-commits-automation-for-jira-and-workflow-triggers-setting-gij-cloud.md

GIT-5270 / GITCL-3418 Update smart commits info in General settings

---

git-integration-for-jira-cloud/github-webhook-indexing-integration-gij-cloud.md
git-integration-for-jira-cloud/gitlab-webhook-indexing-integration-gij-cloud.md
git-integration-for-jira-cloud/microsoft-webhook-indexing-integration-gij-cloud.md

Give important infos some attention format

GIT-5333 / GITCL-3418 Update info, formatting and notes

---

git-integration-for-jira-cloud/app-support-gij-cloud.md
git-integration-for-jira-cloud/manager-permissions-gij-cloud.md

add new page for permalink to manager-permissions-gij-cloud.md 
update version support info to 9.11

GITCL-3534

---

git-integration-for-jira-cloud/Documentation-gij-cloud.md
git-integration-for-jira-cloud/managing-integration-or-repository-configuration-gij-cloud.md

update doc version
fix missing img
merge to 4.23 branch

GIT-5383 / GITCL-3418

---

git-integration-for-jira-cloud/Documentation-gij-cloud.md
git-integration-for-jira-cloud/managing-integration-or-repository-configuration-gij-cloud.md

Git 5333 update docs main v423 cloud

---

git-integration-for-jira-cloud/microsoft-vsts-tfs-azure-repos-jmespath-filter-examples-gij-cloud.md

Update JMESPath examples for MS/Azure

GIT-5383 / GITCL-3602

---

git-integration-for-jira-cloud/enable-git-integration-app-smart-commits-setting-gij-cloud.md
git-integration-for-jira-cloud/enable-jira-cloud-smart-commits-automation-for-jira-and-workflow-triggers-setting-gij-cloud.md

Add notes for smart commits general setting options Add notes for the difference between these settings

GIT-5383 / GITCL-3418 Add notes for smart commits general settings

---

git-integration-for-jira-cloud/allow-list-whitelist-bigbrassband-cloud-gij-cloud.md
git-integration-for-jira-cloud/manager-permissions-gij-cloud.md

Fix line spacing
Fix bad url formatting

GIT-5383 / GITCL-3471 Formatting and missing element fixes

---

git-integration-for-jira-cloud/SLA-terms-and-conditions-gij-cloud.md

DO NOT MERGE YET
Waiting for review and further corrections.

HC-116 Add draft for updated SLA/Terms and Conditions

---

git-integration-for-jira-cloud/manager-permissions-gij-cloud.md

DO NOT MERGE YET...
Feature and API testing.....

Git 5433 admin delegation

---

git-integration-for-jira-cloud/Getting-Started-Guide.md

Ken and I are linking to this guide from the in-app user flow. Reworking the intro page to encourage users to read on

Formalize intro to guide

---

git-integration-for-jira-cloud/gitlab-ce-ee-gij-cloud.md

auto PAT rotation
forgot to push this sooner

GIT-6001 Add/update info

---

git-integration-for-jira-cloud/cicd-getting-started-with-ci-cd-for-jira-gij-cloud.md
git-integration-for-jira-cloud/cicd-how-to-enable-deployment-view-in-jira-gij-cloud.md
git-integration-for-jira-cloud/cicd-viewing-builds-and-deployments-in-a-jira-issue-gij-cloud.md

minor fixes to wordings and conjunctions
add some info on pipelines and some minor wording fixes

Git 6102 5 1 x docs main

---

git-integration-for-jira-cloud/associating-project-permissions-gij-cloud.md
git-integration-for-jira-cloud/edit-integration-gij-cloud.md
git-integration-for-jira-cloud/edit-nested-repository-settings-gij-cloud.md
git-integration-for-jira-cloud/edit-repository-gij-cloud.md
git-integration-for-jira-cloud/managing-integrations-via-actions-jira-cloud-gij-cloud.md
git-integration-for-jira-cloud/remove-a-nested-repository-gij-cloud.md
git-integration-for-jira-cloud/removing-integration-or-repository-configuration-gij-cloud.md
git-integration-for-jira-cloud/ssl-verify-gij-cloud.md
git-integration-for-jira-cloud/view-repository-indexing-logs-gij-cloud.md

Fix footer links
Add HC menu items

GIT-6102 Update title names

---

git-integration-for-jira-cloud/allow-list-whitelist-bigbrassband-cloud-gij-cloud.md

The reachable network address examples does not display correctly. I fixed it by putting the examples inside a table.

Allow list page -- Fix display issues
